apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifact-id:
        type: string
        required: true
      environment:
        type: string
        required: true
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  deploy:
    uses: aspm-app-dashboard/reusableworkflows/MyAppDeploy.yaml
    with:
      artifact-id: ${{ inputs.artifact-id }}
      environment: ${{ inputs.environment }}
